**What Is A Tensor?**

The inputs, outputs, and transformations within neural networks are all represented using tensors, and as a result, neural network programming utilizes tensors heavily.

Specific Instances Of Tensors
Each of these examples are specific instances of the more general concept of a tensor:

*   number
*   scalar
*   array
*   vector
*   2d-array
*   matrix

Let's organize the above list of example tensors into two groups:

*   number, array, 2d-array
*   scalar, vector, matrix

The first group of three terms (number, array, 2d-array) are terms that are typically used in computer science, while the second group (scalar, vector, matrix) are terms that are typically used in mathematics.

Mathematics

In mathematics, we stop using words like scalar, vector, and matrix, and we start using the word tensor or nd-tensor. The  tells us the number of indexes required to access a specific element within the structure.

Computer Science

In computer science, we stop using words like, number, array, 2d-array, and start using the word multidimensional array or nd-array. The  tells us the number of indexes required to access a specific element within the structure.


Indexes_required  Computer_science	 Mathematics
    
     n              nd-array	       nd-tensor

Let's make this clear. For practical purposes in neural network programming, tensors and nd-arrays are one in the same.

Tensors and nd-arrays are the same thing!

So tensors are multidimensional arrays or nd-arrays for short. The reason we say a tensor is a generalization is because we use the word tensor for all values of  like so:

A scalar is a  dimensional tensor

A vector is a  dimensional tensor

A matrix is a  dimensional tensor

A nd-array is an  dimensional tensor

Tensors allow us to drop these specific terms and just use an  to identify the number of dimensions we are working with.


Reference - 1.https://deeplizard.com/learn/video/Csa5R12jYRg#:~:text=A%20tensor%20is%20the%20primary,of%20other%20more%20specific%20concepts.

2.https://medium.com/mlait/tensors-representation-of-data-in-neural-networks-bbe8a711b93b

3.https://www.tensorflow.org/tutorials/customization/basics

In [2]:
import tensorflow as tf

In [6]:
# Scalar or Rank 0 or 0-D Tensors
a = tf.Variable(451, tf.int16)
b = tf.Variable(3.14159265359, tf.float64)
c = tf.Variable(12.3-4.85j, tf.complex64)

In [7]:
print(type(a))
print(a)
print(type(b))
print(b)
print(type(c))
print(c)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


In [8]:
# Vector or Rank 1 or 1-D Tensors
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)

In [9]:
print(type(mymat))
print(mymat)
print(type(myxor))
print(myxor)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>


In [10]:
# 3-D Tensor and Higher Dimensional Tensor
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [11]:
print(type(mymat))
print(mymat)
print(type(myxor))
print(myxor)
print(type(linear_squares))
print(linear_squares)
print(type(squarish_squares))
print(squarish_squares)
print(type(rank_of_squares))
print(rank_of_squares)
print(type(mymatC))
print(mymatC)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[ 4],
       [ 9],
       [16],
       [25]], dtype=int32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(2, shape=(), dtype=int32)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>


In [12]:
# Different operations can be done with tensors
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [13]:
# Each tensor have a shape and datatype
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [14]:
# Numpy arrays can be converted to tensors and vice versa

import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [15]:
# Tensors can be supported with GPU acceleration
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU #0:  
False


In [3]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 412.38ms
On GPU:
10 loops: 2040.93ms
