In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Max-Min
import numpy

# creating a numpy array of integers
arr = numpy.array([1, 5, 4, 8, 3, 7])

# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)

# printing the result
print('maximum element in the array is: ',
	max_element)
print('minimum element in the array is: ',
	min_element)


maximum element in the array is:  8
minimum element in the array is:  1


In [6]:
# Random Number Generation
from numpy import random

x = random.randint(100)

print(x)

14


In [7]:
# Random Number Generation - float
from numpy import random

x = random.rand()

print(x)

0.002668696445327301


In [8]:
# Random Number Generation - Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[ 3 67 65 89 49]


In [9]:
# Random Number Generation - 2D Array
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[93 78 31  4 54]
 [ 4  1 67 96 25]
 [38 46 72 17  4]]


In [10]:
#Scalar -  Python program explaining
# numpy.asscalar() function

import numpy as geek
# creating a array of size 1
in_arr = geek.array([ 8 ])

print ("Input array : ", in_arr)

	
out_scalar = geek.asscalar(in_arr)
print ("output scalar from input array : ", out_scalar)


Input array :  [8]
output scalar from input array :  8


<ipython-input-10-237e0a90ff51>:11: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = geek.asscalar(in_arr)


In [12]:
# Vector
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [1, 2, 3]

# creating a 1-D list (Vertical)
list2 = [[10],
		[20],
		[30]]

# creating a vector1
# vector as row
vector1 = np.array(list1)

# creating a vector 2
# vector as column
vector2 = np.array(list2)


# showing horizontal vector
print("Horizontal Vector")
print(vector1)

print("----------------")

# showing vertical vector
print("Vertical Vector")
print(vector2)


Horizontal Vector
[1 2 3]
----------------
Vertical Vector
[[10]
 [20]
 [30]]


In [13]:
# Python Program illustrating
# numpy.matrix class

import numpy as geek

# string input
a = geek.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")

# array-like input
b = geek.matrix([[5, 6, 7], [4, 6]])
print("Via array-like input : \n", b)


Via string input : 
 [[1 2]
 [3 4]] 


Via array-like input : 
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\User\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


In [14]:
# input two matrices of size n x m
matrix1 = [[12,7,3],
		[4 ,5,6],
		[7 ,8,9]]
matrix2 = [[5,8,1],
		[6,7,3],
		[4,5,9]]

res = [[0 for x in range(3)] for y in range(3)]

# explicit for loops
for i in range(len(matrix1)):
	for j in range(len(matrix2[0])):
		for k in range(len(matrix2)):

			# resulted matrix
			res[i][j] += matrix1[i][k] * matrix2[k][j]

print (res)


[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In [15]:
# We need install numpy in order to import it
import numpy as np

# input two matrices
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

# This will return dot product
res = np.dot(mat1,mat2)


# print resulted matrix
print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [17]:
# Python Program illustrating
# numpy.amin() method

import numpy as geek

# 1D array
arr = geek.arange(8)
print("arr : ", arr)
print("Min of arr : ", geek.amin(arr))

# 2D array
arr = geek.arange(10).reshape(2, 5)
print("\narr : ", arr)

# Minimum of the flattened array
print("\nMin of arr, axis = None : ", geek.amin(arr))

# Minimum along the first axis
# axis 0 means vertical
print("Min of arr, axis = 0 : ", geek.amin(arr, axis = 0))

# Minimum along the second axis
# axis 1 means horizontal
print("Min of arr, axis = 1 : ", geek.amin(arr, axis = 1))


arr :  [0 1 2 3 4 5 6 7]
Min of arr :  0

arr :  [[0 1 2 3 4]
 [5 6 7 8 9]]

Min of arr, axis = None :  0
Min of arr, axis = 0 :  [0 1 2 3 4]
Min of arr, axis = 1 :  [0 5]


In [18]:
# Python Program illustrating
# numpy.amax() method

import numpy as geek

# 1D array
arr = geek.arange(8)
print("arr : ", arr)
print("Max of arr : ", geek.amax(arr))

# 2D array
arr = geek.arange(10).reshape(2, 5)
print("\narr : ", arr)

# Maximum of the flattened array
print("\nMax of arr, axis = None : ", geek.amax(arr))

# Maxima along the first axis
# axis 0 means vertical
print("Max of arr, axis = 0 : ", geek.amax(arr, axis = 0))

# Maxima along the second axis
# axis 1 means horizontal
print("Max of arr, axis = 1 : ", geek.amax(arr, axis = 1))


arr :  [0 1 2 3 4 5 6 7]
Max of arr :  7

arr :  [[0 1 2 3 4]
 [5 6 7 8 9]]

Max of arr, axis = None :  9
Max of arr, axis = 0 :  [5 6 7 8 9]
Max of arr, axis = 1 :  [4 9]


In [19]:
# import numpy library
import numpy

# creating a numpy array of integers
arr = numpy.array([1, 5, 4, 8, 3, 7])

# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)

# printing the result
print('maximum element in the array is: ',
	max_element)
print('minimum element in the array is: ',
	min_element)


maximum element in the array is:  8
minimum element in the array is:  1
