In [1]:
class Pet(object):
   def my_method(self):
      print("I am a Cat")
cat = Pet()
cat.my_method()

I am a Cat


In [2]:
import numpy

In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# import numpy library
import numpy

# creating a numpy array of integers
arr = numpy.array([1, 5, 4, 8, 3, 7])

# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)

# printing the result
print('maximum element in the array is: ',
	max_element)
print('minimum element in the array is: ',
	min_element)


maximum element in the array is:  8
minimum element in the array is:  1


In [6]:
from numpy import random

x = random.randint(100)

print(x)

36


In [7]:
from numpy import random

x = random.randint(100)

print(x)

55


In [8]:
from numpy import random

x = random.rand()

print(x)

0.9274824796459412


In [9]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[43 78 57 85  2]


In [10]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[64 16 96 33 92]
 [ 7 38 81 64 27]
 [30 96 65 70 66]]


In [11]:
# Python Program illustrating
# numpy.matrix class

import numpy as edunet

# string input
a = edunet.matrix('1 2; 3 4')
print("Via string input : \n", a, "\n\n")

# array-like input
b = edunet.matrix([[5, 6, 7], [4, 6]])
print("Via array-like input : \n", b)

Via string input : 
 [[1 2]
 [3 4]] 


Via array-like input : 
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\user\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


In [12]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [1, 2, 3]

# creating a 1-D list (Vertical)
list2 = [[10],
		[20],
		[30]]

# creating a vector1
# vector as row
vector1 = np.array(list1)

# creating a vector 2
# vector as column
vector2 = np.array(list2)


# showing horizontal vector
print("Horizontal Vector")
print(vector1)

print("----------------")

# showing vertical vector
print("Vertical Vector")
print(vector2)


Horizontal Vector
[1 2 3]
----------------
Vertical Vector
[[10]
 [20]
 [30]]


In [13]:
# Python program explaining
# numpy.asscalar() function

import numpy as edunet
# creating a array of size 1
in_arr = edunet.array([ 8 ])

print ("Input array : ", in_arr)

	
out_scalar = edunet.asscalar(in_arr)
print ("output scalar from input array : ", out_scalar)


Input array :  [8]
output scalar from input array :  8


<ipython-input-13-2052f4822ffd>:11: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = edunet.asscalar(in_arr)


In [14]:
import numpy as np

# input two matrices
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

# This will return dot product
res = np.dot(mat1,mat2)


# print resulted matrix
print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [15]:
import numpy as np
arr= np.array([[1,23,78],[98,60,75],[79,25,48]])  
print(arr)
#Minimum Function
print(np.amin(arr))
#Maximum Function
print(np.amax(arr))

[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [16]:
import numpy as np
a = np.array([5,6,7]) 
print(a)
print(np.mean(a))

[5 6 7]
6.0


In [17]:
import numpy as np
a = np.array([5,6,7]) 
print(a)
print(np.median(a))

[5 6 7]
6.0


In [18]:
import numpy as np
a = np.array([5,6,7]) 
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


In [19]:
import numpy as np
a = np.array([5,6,7]) 
print(a)
print(np.var(a))

[5 6 7]
0.6666666666666666


In [20]:
import numpy as np

data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97,
		101, 105, 112, 116]

# First quartile (Q1)
Q1 = np.median(data[:10])

# Third quartile (Q3)
Q3 = np.median(data[10:])

# Interquartile range (IQR)
IQR = Q3 - Q1

print(IQR)


34.0


In [21]:
# Import numpy library
import numpy as np

data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97,
		101, 105, 112, 116]

# First quartile (Q1)
Q1 = np.percentile(data, 25, interpolation = 'midpoint')

# Third quartile (Q3)
Q3 = np.percentile(data, 75, interpolation = 'midpoint')

# Interquaritle range (IQR)
IQR = Q3 - Q1

print(IQR)


34.0


In [22]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [23]:
from numpy import array
a = array([1.0, 2.0, 3.0])
b = array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [24]:
from numpy import array
a = array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [25]:
import numpy as np

# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)		
print ("Along first axis : \n", arr1)		


# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)		
print ("\nAlong first axis : \n", arr2)


a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)		
print ("\nAlong none axis : \n", arr1)


Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]
